# This is a basic workflow to help you get started with Actions

name: bothost

on:

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run a Python app
        run: python main.py
