# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: bothost

on: 
  workflow_dispatch:


env:
  bot_token: ${{ secrets.BOT_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Install jq tool
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get install jq
    - name: Install Modules
      run: |
        pip install git+https://github.com/DisnakeDev/disnake.git
        pip install os
    - name: Run Bots Code
      run: python main.py
   
  
